import os
from multiply_module import *
#When importing your module, Python will read (or create if it does not exist) a .pyc file. From version 3.2, this
#file is located in a __pycache__ folder.
"""
Also: .pyc=> This file is generated by Python and contains the compiled code (or almost) of your module. It's not really about language
machine but in a format that Python decodes a little faster than code you can write. Python loads itself
to generate this file and you don't really need to worry about it when you code, just don't be surprised.
"""
# table function test
table(3, 20)
os.system("pause")
